In [27]:
import casadi
from numpy import pi
import numpy as np

opti = casadi.Opti()

sin2 = opti.variable()
cos2 = opti.variable()
sin3 = opti.variable()
cos3 = opti.variable()

L1, L2, L3, L4, theta1 = (1, 2.5, 2.5, 2, 5/4*pi)
sin1, cos1 = (np.sin(theta1), np.cos(theta1))

opti.minimize(  (L1*sin1 + L2*sin2 + L3*sin3)**2 + (L1*cos1 + L2*cos2 + L3*cos3 - L4)**2)
opti.subject_to( sin2**2 + cos2**2==1 )
opti.subject_to( sin3**2 + cos3**2==1 )
# opti.subject_to(       x+y>=1 )

        # L1*sin1 + L2*sin2 + L3*sin3,
        # L1*cos1 + L2*cos2 + L3*cos3 - L4, 
        # sin2**2 + cos2**2 - 1,
        # sin3**2 + cos3**2 - 1,    


# (L1*sin1 + L2*sin2 + L3*sin3)**2 + (L1*cos1 + L2*cos2 + L3*cos3 - L4)**2 + (sin2**2 + cos2**2 - 1)**2 + (sin3**2 + cos3**2 - 1)**2


opti.solver('ipopt')


sol = opti.solve()

print(sol.value(sin2), sol.value(cos2), sol.value(sin3), sol.value(cos3))

sol.value((L1*sin1 + L2*sin2 + L3*sin3)**2 + (L1*cos1 + L2*cos2 + L3*cos3 - L4)**2)


This is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        6

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        2
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  7.8284271e+00 1.00e+00 1.35e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00 

4.849100605428057

In [23]:
from casadi import *
opti = Opti()

m_l = 0.5 #mass to push off ground
k = 3000 #spring stiffness
tau_max = 0.05 #N*m stall torque
omega_max = 3000 #about 10,000rpm free speed
t = 0.2

T1 = opti.variable()
T2 = opti.variable()

sqrt_x = if_else(x>0, [sqrt(x), 0], [0, -sqrt(x)])   # sqrt_x is a 2-vector
cos_z = ([z[0]*sin(z[1]),  z[0]*cos(z[1])] + [z[0]*sin(z[1]),  -z[0]*cos(z[1])]) / 2


r = -T1**4*T2**2*k**2*m_l**2*omega_max**2 + 4*k*m_l*tau_max**2
sqrt_r_re = if_else(r>0, sqrt(r), 0)
sqrt_r_im = if_else(r>0, 0, -sqrt(r))

cos_r(t/(2*T2*m_l*tau_max)) * sqrt_r_re

opti.minimize(-A[0]*A[1])
opti.subject_to(opti.bounded(0, x+y, 10))

opti.solver('ipopt')
sol = opti.solve()

print(sol.value(x), sol.value(y))


# z = MX([x[0],2])
# z
# z = if_else(x > 0, SX([sqrt(x), 0]), SX([0, sqrt(-x)]))
# cos_z = (SX([z[0]*sin(z[1]),  z[0]*cos(z[1])]) + SX([z[0]*sin(z[1]),  -z[0]*cos(z[1])])) / 2
# cos_z

This is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        2
Number of nonzeros in Lagrangian Hessian.............:        1

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        1
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 -0.0000000e+00 0.00e+00 0.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00 

In [27]:
np.cos(np.sqrt(complex(-1)))

(1.5430806348152437-0j)

In [39]:
from numpy import sin, cos, sqrt, exp, cosh, sinh

m_l = 0.5 #mass to push off ground
k = 3000 #spring stiffness
tau_max = 0.05 #N*m stall torque
omega_max = 3000 #about 10,000rpm free speed
t = 0.2

x_a0, x_l0, v_l0 = (0,0,0)

# 0.0003367768532824227 5.362632380167144 5.113164058144344
# T1 = 0.0003367
# T2 = 5.3626
T1, T2 = (0.0003, 5.362632246568017)

x0 = 1/T2
x1 = T2**2
x2 = omega_max**2
x3 = x1*x2
x4 = k**2
x5 = m_l**2
x6 = T1**4*x5
x7 = x4*x6
x9 = 1/tau_max
x10 = (1/2)*x9
x12 = T1**2
x13 = omega_max*t
x14 = k*x10*x12*x13
x15 = exp(x14)
x16 = tau_max*x15
x17 = x16*x_a0
x18 = T1*omega_max
x19 = T2*m_l*v_l0*x18
x20 = m_l*x12
x21 = x20*x3
x22 = k*m_l
x23 = 2*tau_max
x24 = x23*x_l0
x25 = x12*x22
x26 = x23*x_a0
x27 = T2*omega_max
x28 = T2**3
x29 = omega_max**3
x30 = T1**3
x32 = exp(-x14)
x33 = x32*x9
x34 = x1*x18
x35 = T2*v_l0 - x34
x36 = 2*k
x37 = T1*T2
x38 = omega_max*x1
x39 = 2*v_l0*x25*x38
x40 = x2*x28
x41 = x22*x30*x40
x42 = 2*x41
x43 = tau_max*x36
x44 = -x37*x43*x_a0 + x43*x_l0

#complex operations below this point
R_ad = sqrt(complex(4*k*m_l*tau_max**2 - x3*x7))
x11 = t*x0*x10*R_ad/m_l

S_in = sin(x11)
C_os = cos(x11)

print(f"R_ad: {R_ad}")
print(f"S_in: {S_in}")
print(f"C_os: {C_os}")


x31 = S_in/R_ad
x_a = x33*(C_os*(-x19 + x21) + x13*x16 + x15*x19 - x15*x21 + x17 + x31*(-k*v_l0*x3*x30*x5 + k*x28*x29*x6 + x18*x22*x24 - x25*x26*x27))
x_l = (1/2)*x33*(C_os*(-x39 + x42 + x44) + R_ad*S_in*x35 + T2*t*x16*x18*x36 + x15*x39 - x15*x42 + x17*x36*x37 + x31*(T1**5*T2**4*x29*x4*x5 - m_l*x26*x30*x38*x4 - v_l0*x40*x7 + x20*x24*x27*x4))/k
v_l = x0*x32*(C_os*x35 + x15*x34 + x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44))

print(f"x31: {x31}")
print(f"C_os*x35: {C_os*x35}")
print(f"x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44): {x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44)}")
print(f"C_os*x35 + x15*x34 + x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44): {C_os*x35 + x15*x34 + x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44)}")

print('solutions', x_a, x_l, v_l)


R_ad: (3.206711371175772+0j)
S_in: (0.6814185661901562+0j)
C_os: (-0.7318939387994354-0j)
x31: (0.21249762991307425+0j)
C_os*x35: (18.942909773876664+0j)
x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44): (-11.944986664643388+0j)
C_os*x35 + x15*x34 + x31*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44): (137.7822196740254+0j)
solutions (354.59770172691805+0j) (0.5160522391767082+0j) (5.084615311406588+0j)


In [38]:
from math import sin, cos, sqrt, exp, cosh, sinh

m_l = 0.5 #mass to push off ground
k = 3000 #spring stiffness
tau_max = 0.05 #N*m stall torque
omega_max = 3000 #about 10,000rpm free speed
t = 0.2

x_a0, x_l0, v_l0 = (0,0,0)

# 0.0003367768532824227 5.362632380167144 5.113164058144344
# T1 = 0.0003367
# T2 = 5.3626
T1, T2 = (0.0003, 5.362632246568017)

x0 = 1/T2
x1 = T2**2
x2 = omega_max**2
x3 = x1*x2
x4 = k**2
x5 = m_l**2
x6 = T1**4*x5
x7 = x4*x6
x9 = 1/tau_max
x10 = (1/2)*x9
x12 = T1**2
x13 = omega_max*t
x14 = k*x10*x12*x13
x15 = exp(x14)
x16 = tau_max*x15
x17 = x16*x_a0
x18 = T1*omega_max
x19 = T2*m_l*v_l0*x18
x20 = m_l*x12
x21 = x20*x3
x22 = k*m_l
x23 = 2*tau_max
x24 = x23*x_l0
x25 = x12*x22
x26 = x23*x_a0
x27 = T2*omega_max
x28 = T2**3
x29 = omega_max**3
x30 = T1**3
x32 = exp(-x14)
x33 = x32*x9
x34 = x1*x18
x35 = T2*v_l0 - x34
x36 = 2*k
x37 = T1*T2
x38 = omega_max*x1
x39 = 2*v_l0*x25*x38
x40 = x2*x28
x41 = x22*x30*x40
x42 = 2*x41
x43 = tau_max*x36
x44 = -x37*x43*x_a0 + x43*x_l0

r = 4*k*m_l*tau_max**2 - x3*x7

R_ad_re = sqrt(r) if r > 0 else 0
R_ad_im = 0 if r>0 else sqrt(-r)
# R_ad_re = if_else(r>0, sqrt(r), 0)
# R_ad_im = if_else(r>0, 0, -sqrt(r))

x11_re = t*x0*x10*R_ad_re/m_l
x11_im = t*x0*x10*R_ad_im/m_l

C_os = cos(x11_re)*cosh(x11_im)
S_in_re = sin(x11_re)*cosh(x11_im)
S_in_im = cos(x11_re)*sinh(x11_im)

SdR = (S_in_re*R_ad_re + S_in_im*R_ad_im) / (R_ad_re**2 + R_ad_im**2) # S_in/R_ad should be purely real (aka x31)
SmR = S_in_re*R_ad_re - S_in_im*R_ad_im  # S_in*R_ad should be purely real

x_a = x33*(C_os*(-x19 + x21) + x13*x16 + x15*x19 - x15*x21 + x17 + SdR*(-k*v_l0*x3*x30*x5 + k*x28*x29*x6 + x18*x22*x24 - x25*x26*x27))
x_l = (1/2)*x33*(C_os*(-x39 + x42 + x44) + SmR*x35 + T2*t*x16*x18*x36 + x15*x39 - x15*x42 + x17*x36*x37 + SdR*(T1**5*T2**4*x29*x4*x5 - m_l*x26*x30*x38*x4 - v_l0*x40*x7 + x20*x24*x27*x4))/k
v_l = x0*x32*(C_os*x35 + x15*x34 + SdR*(k*m_l*omega_max*v_l0*x1*x12 - x41 - x44))

print(x_a, x_l, v_l)



R_ad: 3.206711371175772, 0
S_in: 0.6814185661901562, -0.0
C_os: -0.7318939387994354
SmR: 2.1851126647322645, 0.0
354.59770172691805 0.5160522391767082 5.084615311406588


In [131]:
from casadi import *
import numpy as np

X0 = SX.sym('X0', 3)
T = SX.sym('T', 2)
X_new = SX.sym('X_new', 3)
T1 = T[0]
T2 = T[1]
x_a0 = X0[0]
x_l0 = X0[1]
v_l0 = X0[2]
#calcs
x_a = x_a0 + T1
x_l = x_l0 + T2
v_l = v_l0 + T1 + T2
X_new[0] = x_a
X_new[1] = x_l
X_new[2] = v_l

step = Function("step", [X0, T], [X_new])

opti = Opti()
Ts = opti.variable(2, 3) #column vectors of [T1, T2], concat horizontally nsteps number of times

X_init = (0,0,0)
# X1 = step(X_init, Ts[0,:])
# X2 = step(X1, Ts[1,:])
# X3 = step(X2, Ts[2,:])

fX3_fold = step.fold(3)
X3_fold = fX3_fold(X_init, Ts)

F = X3_fold[2]

opti.minimize(-F)
opti.subject_to(opti.bounded(0, Ts[0,:], 2))
opti.subject_to(opti.bounded(0, Ts[1,:], 3))
opti.set_initial(Ts, 1)

log = []
opti.callback(lambda i: log.append(opti.debug.value(Ts)))
opti.solver('ipopt', {'ipopt.print_level':0, 'print_time':0})
sol = opti.solve()

print(sol.value(Ts), sol.value(F))
print(np.array(log))

[[2.00000002 2.00000002 2.00000002]
 [3.00000003 3.00000003 3.00000003]] 15.00000013495609
[[[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.50000001 1.50000001 1.50000001]
  [1.70000001 1.70000001 1.70000001]]

 [[1.88607014 1.88607014 1.88607014]
  [2.98700003 2.98700003 2.98700003]]

 [[1.99967778 1.99967778 1.99967778]
  [2.9973878  2.9973878  2.9973878 ]]

 [[1.99984938 1.99984938 1.99984938]
  [2.99984743 2.99984743 2.99984743]]

 [[1.99999816 1.99999816 1.99999816]
  [2.99999818 2.99999818 2.99999818]]

 [[2.00000002 2.00000002 2.00000002]
  [3.00000003 3.00000003 3.00000003]]]


In [106]:
X0 = SX.sym('X0', 3)
T = SX.sym('T', 2)
X_new = SX.sym('X_new', 3)
T1 = T[0]
T2 = T[1]
x_a0 = X0[0]
x_l0 = X0[1]
v_l0 = X0[2]
#calcs
x_a = x_a0 + T1
x_l = x_l0 + T2
v_l = v_l0 + T1 + T2
X_new[0] = x_a
X_new[1] = x_l
X_new[2] = v_l

step = Function("step", [X0, T], [X_new])


X_init = (0,0,0)
X1 = step(X_init, (2,1))
X2 = step(X1, (2,2))
X3 = step(X2, (2,2))
print(X_init, X1, X2, X3)

(0, 0, 0) [2, 1, 3] [4, 3, 7] [6, 5, 11]


In [142]:
nsteps = 3

k = SX.sym('k')
X0 = SX.sym('X0', 5)
x_a0 = X0[0]
x_l0 = X0[1]
v_l0 = X0[2]
T = SX.sym('T', 2)
T1 = T[0]
T2 = T[1]
X_new = SX.sym('X_new', 5)
X_new = SX.sym('X_new', 5)
X_new[0] = x_a0 + k
X_new[1] = x_l0
X_new[2] = v_l0
X_new[3] = T1
X_new[4] = T2

Fstep = Function("step", [X0, T, k], [X_new])
Fstep_n = Fstep.mapaccum(nsteps)


Fstep_n([0,0,0,0,0], [1,2], 2)


# ''' Optimization '''
# opti = Opti()

# Ts = opti.variable(2, nsteps) #column vectors of [T1, T2], concat horizontally
# k_var = opti.variable() #column vectors of [T1, T2], concat horizontally

# X0 = 
# X_n = Fstep_n([], Ts, k)

DM(
[[2, 4, 6], 
 [0, 0, 0], 
 [0, 0, 0], 
 [1, 1, 1], 
 [2, 2, 2]])