In [53]:
from sympy import *

L1, L2, L3, L4, sin1, cos1 = symbols("L1, L2, L3, L4, sin1, cos1")

sin2, cos2, sin3, cos3 = symbols("sin2, cos2, sin3, cos3")

f = Matrix([
    L1*sin1 + L2*sin2 + L3*sin3,
    L1*cos1 + L2*cos2 + L3*cos3 - L4, 
    sin2**2 + cos2**2 - 1,
    sin3**2 + cos3**2 - 1,        
])


J = Matrix([
    [L2, 0, L3, 0],
    [0, L2, 0, L3],
    [2*sin2, 2*cos2, 0, 0],
    [0, 0, 2*sin3, 2*cos3]
])

h = simplify(-J.inv()*f)
# for h_ in h:
#     print(h_)
print(h)
h

Matrix([[(L2*cos3*(cos2**2 + sin2**2 - 1) + L3*cos2*(cos3**2 + sin3**2 - 1) - 2*cos2*(cos3*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin3*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L2*(cos2*sin3 - cos3*sin2))], [(-L2*sin3*(cos2**2 + sin2**2 - 1) - L3*sin2*(cos3**2 + sin3**2 - 1) + 2*sin2*(cos3*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin3*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L2*(cos2*sin3 - cos3*sin2))], [(-L2*cos3*(cos2**2 + sin2**2 - 1) - L3*cos2*(cos3**2 + sin3**2 - 1) + 2*cos3*(cos2*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin2*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L3*(cos2*sin3 - cos3*sin2))], [(L2*sin3*(cos2**2 + sin2**2 - 1) + L3*sin2*(cos3**2 + sin3**2 - 1) - 2*sin3*(cos2*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin2*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L3*(cos2*sin3 - cos3*sin2))]])


Matrix([
[ (L2*cos3*(cos2**2 + sin2**2 - 1) + L3*cos2*(cos3**2 + sin3**2 - 1) - 2*cos2*(cos3*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin3*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L2*(cos2*sin3 - cos3*sin2))],
[(-L2*sin3*(cos2**2 + sin2**2 - 1) - L3*sin2*(cos3**2 + sin3**2 - 1) + 2*sin2*(cos3*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin3*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L2*(cos2*sin3 - cos3*sin2))],
[(-L2*cos3*(cos2**2 + sin2**2 - 1) - L3*cos2*(cos3**2 + sin3**2 - 1) + 2*cos3*(cos2*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin2*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L3*(cos2*sin3 - cos3*sin2))],
[ (L2*sin3*(cos2**2 + sin2**2 - 1) + L3*sin2*(cos3**2 + sin3**2 - 1) - 2*sin3*(cos2*(L1*cos1 + L2*cos2 + L3*cos3 - L4) + sin2*(L1*sin1 + L2*sin2 + L3*sin3)))/(2*L3*(cos2*sin3 - cos3*sin2))]])

In [31]:
#known
L1, L2, L3, L4, theta1 = symbols("L1, L2, L3, L4, theta1")

#unknown
theta2, theta3 = symbols("theta2, theta3")

f_angles = Matrix([
    L1*sin(theta1) + L2*sin(theta2) + L3*sin(theta3),
    L1*cos(theta1) + L2*cos(theta2) + L3*cos(theta3) - L4
])

J_angles = Matrix([
    [L2*cos(theta2), L3*cos(theta3)],
    [-L2*sin(theta2), -L3*sin(theta3)]
])

simplify(-J.inv()*f)

Matrix([
[ (L1*cos(theta1 - theta3) + L2*cos(theta2 - theta3) + L3 - L4*cos(theta3))/(L2*sin(theta2 - theta3))],
[(-L1*cos(theta1 - theta2) - L2 - L3*cos(theta2 - theta3) + L4*cos(theta2))/(L3*sin(theta2 - theta3))]])

In [51]:
import numpy as np
from numpy import sin, cos, pi

L1, L2, L3, L4, theta1 = (1, 2.5, 2.5, 2, 5/4*pi)

# Initialize variables and parameters
x0 = np.array((1,0))
tolerance = 1e-6
max_iterations = 100

# Newton-Raphson iterations
for iteration in range(max_iterations):
    theta2, theta3 = x0
    h = [
        (L1*cos(theta1-theta3) + L2*cos(theta2-theta3) + L3 - L4*cos(theta3)) / (L2*(theta2-theta3)),
        (-L1*cos(theta1-theta2) - L2 - L3*cos(theta2-theta3) + L4*cos(theta2)) / (L3*(theta2-theta3))
    ]
    x_new = x0 + h

    print(x_new)

    if np.linalg.norm(x_new - x0) < tolerance:
        break

    x0 = x_new

print("Solution:", np.mod(x0, 2*pi))

[ 1.45745959 -0.71723596]
[ 1.36641216 -0.73041127]
[ 1.30918023 -0.73096665]
[ 1.27501967 -0.72822456]
[ 1.2555326 -0.7255862]
[ 1.24477906 -0.72378834]
[ 1.23897046 -0.72271478]
[ 1.23587227 -0.72211259]
[ 1.23423143 -0.7217853 ]
[ 1.23336577 -0.72161029]
[ 1.23291001 -0.7215175 ]
[ 1.23267032 -0.72146852]
[ 1.23254434 -0.72144272]
[ 1.23247814 -0.72142916]
[ 1.23244336 -0.72142203]
[ 1.23242509 -0.72141828]
[ 1.2324155  -0.72141631]
[ 1.23241046 -0.72141528]
[ 1.23240781 -0.72141473]
[ 1.23240642 -0.72141445]
[ 1.23240569 -0.7214143 ]
Solution: [1.23240642 5.56177086]


In [52]:
import numpy as np

L1, L2, L3, L4, sin1, cos1 = (1, 2.5, 2.5, 2, -0.707, -0.707)

def func_sincos(vars):
    sin2, cos2, sin3, cos3 = vars
    return [
        L1*sin1 + L2*sin2 + L3*sin3,
        L1*cos1 + L2*cos2 + L3*cos3 - L4, 
        sin2**2 + cos2**2 - 1,
        sin3**2 + cos3**2 - 1,        
    ]

def jac_sincos(vars):
    sin2, cos2, sin3, cos3 = vars
    return [
        [L2, 0, L3, 0],
        [0, L2, 0, L3],
        [2*sin2, 2*cos2, 0, 0],
        [0, 0, 2*sin3, 2*cos3]
    ]

def hess_sincos(vars):
    sin2, cos2, sin3, cos3 = vars
    return [
        [L2, 0, L3, 0],
        [0, L2, 0, L3],
        [2*sin2, 2*cos2, 0, 0],
        [0, 0, 2*sin3, 2*cos3]
    ]

# Initialize variables and parameters
x0 = np.zeros(4)
tolerance = 1e-6
max_iterations = 100

# Newton-Raphson iterations
for iteration in range(max_iterations):
    F = func_sincos(x0)
    J = jac_sincos(x0)
    J_inv = np.linalg.pinv(J)
    x_new = x0 - np.dot(J_inv, F)

    print(x_new)

    if np.linalg.norm(x_new - x0) < tolerance:
        break

    x0 = x_new

print("Solution:", x0)


[0.1414 0.5414 0.1414 0.5414]
[0.155525   0.59548256 0.155525   0.59548256]
[0.15671412 0.60003552 0.15671412 0.60003552]
[0.15681788 0.60043282 0.15681788 0.60043282]
[0.15682696 0.6004676  0.15682696 0.6004676 ]
[0.15682776 0.60047065 0.15682776 0.60047065]
[0.15682783 0.60047091 0.15682783 0.60047091]
Solution: [0.15682776 0.60047065 0.15682776 0.60047065]
